### ISSUE TITLE
Search by name without looking into the contents in the app

### ISSUE THREAD

**Issue by Bekaboo** [SimonSchubert/LinuxCommandLibrary#11]
First thanks for this great app, but occasionally I find it difficult to search for the man page of a command because the app matches the keyword in both the contents and the titles.
For instance, when I want to search for the man page of the command `tar`, the best match entry (man page of `tar`) does not show on the top of the screen:
![Screenshot_20220730_204655_com inspiredandroid linuxcommandbibliotheca](https://user-images.githubusercontent.com/76579810/181914992-e9541499-d366-4e44-bf4a-9cca36436e9e.jpg)

I could not find any settings related to adjust this behavior. It will be great if the app can provide such an option.

**Comment by SimonSchubert** [comment]
I agree, `tar` command should be the very first result in your example. And command name should have a higher priority than content/description.
 
I will look into it when I have time, thanks for the report.

**Comment by SimonSchubert** [comment]
Update is released and should be available in the stores within the next days.

![Screenshot_20220801_202056](https://user-images.githubusercontent.com/1833337/182217268-48b935dd-5f2c-4cbd-a18b-08b5351cd82d.png)

**Comment by Bekaboo** [comment]
> Update is released and should be available in the stores within the next days.
> 
> ![Screenshot_20220801_202056](https://user-images.githubusercontent.com/1833337/182217268-48b935dd-5f2c-4cbd-a18b-08b5351cd82d.png)

Thanks for your work! Cant wait to try it out.
