### ISSUE TITLE
[enhancement] Add entry to Micro text editor

### ISSUE THREAD

**Issue by Vilianexe** [SimonSchubert/LinuxCommandLibrary#15]
Hello, i love the library and i wanted to ask if is possible to add an entry for the [Micro](https://micro-editor.github.io/)  text editor.
It's a modern and intuitive terminal-based text editor, like nano, but a lot more powerful, and extensible
Thanks!

**Comment by SimonSchubert** [comment]
Looks good. I will add it next update. Thanks for the suggestion

**Comment by SimonSchubert** [comment]
Done and will be in the release. Probably will add more content in the future. Thanks again
![image](https://user-images.githubusercontent.com/1833337/205467369-0049f324-e45c-43db-beb9-ae067e36e7e9.png)
