### ISSUE TITLE
find Modified / changed files

### ISSUE THREAD

**Issue by Krediman** [SimonSchubert/LinuxCommandLibrary#20]
In the section *Search & Find* you Have an entry "find modified files since last 60 minutes" and "find changed files since last 60 minutes"
without reading the man page it is pretty unclear what is the difference between a changed and a modified file. 
As a proposal:
find files whose content was modified less than 60 minutes ago
and
find files whose status was changed less than 60 minutes ago

**Comment by SimonSchubert** [comment]
Thanks for the proposal. It makes it definitely more clear. Change will be in the next release
