### ISSUE TITLE
[Commands search]: make search case insensitive

### ISSUE THREAD

**Issue by PetbkA** [SimonSchubert/LinuxCommandLibrary#32]
Although Linux is case sensitive in its essence, searching for commands (and, moreover, their descriptions) shouldn't be.

App's search *is* case sensitive, so by typing e.g. "**I**fconf" I [can't](https://github.com/SimonSchubert/LinuxCommandLibrary/assets/22843816/80b8fa81-52f1-4fc3-a7cb-450eaa422732) find _**i**fconfig_, by typing "**C**onfigure" I can see [only commands](https://github.com/SimonSchubert/LinuxCommandLibrary/assets/22843816/2069f3b6-f73d-417c-8d84-728904ae8d32) with _**C**onfigure_ in description and vice versa.

Searching by command names (not their descriptions) is complicated with the fact that keyboard is always capitalizing first character so I have to set lower case first and then type command name (considering that most of commands are lowercase).

Please make commands search case _in_sensitive

**Comment by SimonSchubert** [comment]
Thanks a lot for the detailed report. Fixed in v3.2.0
