### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by SynapseScribe** [SimonSchubert/LinuxCommandLibrary#6]

**Comment by SimonSchubert** [comment]
Which app version did you try? https://github.com/SimonSchubert/LinuxCommandLibrary/releases/tag/v3.0.1 ? Previous didn't include `database.db` and the missing file seems to be the reason for the crash

**Comment by SimonSchubert** [comment]
Version 3.0.0 (2022-07-05) misses the database but Version 3.0.1 (2022-07-07) looks fine. 

Can you do a fresh install of Version 3.0.1 (2022-07-07)? I just did and works fine for me https://apt.izzysoft.de/fdroid/index/apk/com.inspiredandroid.linuxcommandbibliotheca
