### ISSUE TITLE
Minimal android 7????

### ISSUE THREAD

**Issue by smopro** [SimonSchubert/LinuxCommandLibrary#7]
Just for book you make minimal android 7??? What bad in 4.4?

**Comment by SimonSchubert** [comment]
Minimal sdk for Jetpack Compose is Android 5.0 (API 21) [source](https://developer.android.com/jetpack/compose/setup#groovy) . Why I have chosen 24 I cannot find out right now but I'm happy to come back and report

**Comment by smopro** [comment]
Ouch... I love android 4.4... Can you compile this for linux? Or maybe i have another way to read offline your library?

**Comment by SimonSchubert** [comment]
I would love to release a Linux desktop client. For that I would read/use the man pages installed on the system which will take a bit longer to implement

**Comment by smopro** [comment]
Why not use an existing library from the site? I use man pages not for all installations - some reasons: embedded, miniman instalations. It would be convenient to search for what you need in a single place, especially when you don’t remember or have no idea how to correctly compose a search query. Or just tell me how to compile information from the site into a single fb2 or local html book for reading not only in your application, but also in the console or any reader

**Comment by SimonSchubert** [comment]
That's a good point. Would probably be great to have the option to choose between installed mans and preshipped. Would be necessary to have that "option" for the Mac and windows client anyway.

To build a simple console application should be really easy. I will dig into it when I have time

**Comment by smopro** [comment]
Thx) Console application can be run in terminal emulator on android too)

**Comment by SimonSchubert** [comment]
I hacked together a very basic functionality. Needs some polish before I can release it.

![image](https://user-images.githubusercontent.com/1833337/182043961-f71c7d74-cb26-459b-b1f8-e5b240939d6a.png)

**Comment by SimonSchubert** [comment]
Simple version of CLI is available under the latest release https://github.com/SimonSchubert/LinuxCommandLibrary/releases/tag/v3.0.2

In will try to create a github action to build the jar automatically when I have time.
